apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: kube-system
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'soul1433223@gmail.com'
      smtp_auth_username: 'soul1433223@gmail.com'
      smtp_auth_password: '******123'
      smtp_require_tls: true
    route:
      group_by: ['alertname', 'cluster']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
      receiver: default
      routes:
      - receiver: webhook
        match:
          filesystem: node
      - receiver: email
        group_wait: 10s
        match:
          team: node
    receivers:
    - name: 'default'
      email_configs:
      - to: 'jasontom147@gmail.com'
        send_resolved: true
    - name: 'webhook'
      webhook_configs:
      - url: 'http://alertmanager-webhook:5000'
        send_resolved: true
    - name: 'email'
      email_configs:
      - to: 'soul1433223@gmail.com'
        send_resolved: true
